apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: echo-service
  description: "A simple HTTP echo service, to demonstrate TechDocs"
  annotations:
    # This annotation tells Backstage that the documentation is in the same
    # directory as this catalog-info.yaml file, i.e mkdocs.yaml
    backstage.io/techdocs-ref: dir:.
    # Slug of the GitHub repository that contains this Component's source
    github.com/project-slug: evanshortiss/rhdh-techdocs-example
    # Annotation to use with the Quay.io plugin, if installed in Developer Hub
    quay.io/repository-slug: evanshortiss/httpsink
  tags:
    - api
    - http
    - techdocs
  links:
    - url: https://backstage.io/docs/features/techdocs/
      title: TechDocs Documentation
      icon: web
spec:
  type: service
  owner: guest
  lifecycle: production
  repository: https://github.com/evanshortiss/rhdh-techdocs-example
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: echo-service
  description: "OpenAPI specification for the Echo Service"
  tags:
    - api
    - http
spec:
  type: openapi
  owner: guest
  lifecycle: production
  definition: 
    $text: https://github.com/evanshortiss/rhdh-techdocs-example/blob/main/openapi-spec.json