---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: echo-service
        image: quay.io/evanshortiss/httpsink
        ports:
        - containerPort: 8080
        env:
        - name: SINK_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: echo-service
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  to:
    kind: Service
    name: echo-service
  port:
    targetPort: 8080
  tls:
    termination: edge
